name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Copy files
        run: |
          mkdir gh-pages
          mv src/demo/html/gh-pages.html ./gh-pages/index.html
          mv dist/merge-fields/plugin.min.js ./gh-pages
          mv dist/merge-fields/style.css ./gh-pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: gh-pages